name: release

on:
  push:
    tags:
      - 'v*'  # публикуем только с тегов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # нужно для setuptools-scm видеть теги
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install -U pip build
      - name: Build sdist & wheel
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # prerelease → TestPyPI
      - name: Publish to TestPyPI (for prereleases)
        if: contains(github.ref_name, 'rc')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          repository-url: https://test.pypi.org/legacy/

      # финальный релиз → PyPI
      - name: Publish to PyPI (for final releases)
        if: ${{ !contains(github.ref_name, 'rc') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
